Which of these exception is thrown by close() and read() methods?