Which of these Exceptions is thrown by remote method?